---
- name: Yum updates Excluding Kernel
  gather_facts: false
  become: true
  become_user: oracle
  hosts: dldboran1
  tasks:
    - name: Check current status
      shell: "ps -ef | grep oracle"              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 
