---
- name: Dev Yum updates 
  gather_facts: false
  become: true
  become_user: root
  hosts: dldsadmin1 
         dldsadmin2
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        
