---
# Playbook to apply the latest RHEL updates for DEV and SYSTEST

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot all DEV Servers, Systest Servers 
  gather_facts: false
  hosts: dlaptascob1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
      
# Appy Updates
- name: Dev Yum updates 
  gather_facts: false
  become: true
  become_user: root  
  hosts: dlissplunk1
         dldsadmin1
         dldsadmin2
         dldsansible2
         dldsdev1
         dldsdev2
         dldsproto1
         dldsproto2
         dldsproto3
         dlaptascob1    
         dlaptascob2
         dlapsftp1
         dlapwl1
         tlapwl1
         dlaptasnfs1
         tlaptasnfs1
         dlaporalb1
         dlaporalb2
         tlaporalb1
         tlaporalb2
                                                           
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Stop DEV Splunk before rebooting        
- name: Stop DEV Splunk
  gather_facts: false
  become: true
  become_user: splunk
  hosts: dlissplunk1           
  tasks:
    - name: Stop Splunk
      shell: "/opt/splunk/bin/splunk stop"              
      register: status
    - debug:
       var: status.stdout_lines 

# Reboots excluding DBs
- name: Reboot of Dev Servers
  gather_facts: false
  become: true
  become_user: root
  hosts: dlissplunk1
         dldsadmin1
         dldsadmin2
         dldsansible2
         dldsdev1
         dldsdev2
         dldsproto1
         dldsproto2
         dldsproto3
         dlaptascob1    
         dlaptascob2
         dlapsftp1
         dlapwl1
         tlapwl1
         dlaptasnfs1
         tlaptasnfs1
         dlaporalb1
         dlaporalb2
         tlaporalb1
         tlaporalb2
                                        
  tasks:
  - name: Reboot Dev
    reboot:
