---
# Playbook to apply the latest RHEL updates, switch Load Balancers and Reboots for DEV excluding the Oracle DB's

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot all DEV Servers (Excluding DBs). Cancel immediately if ran in error!
  gather_facts: false
  hosts: dldsadmin1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
      
# Appy Updates
- name: Dev Yum updates 
  gather_facts: false
  become: true
  become_user: root  
  hosts: pdl6sftp01
         dlissplunk1
         dldsadmin1
         dldsadmin2
         dldsansible2
         dldsdev1
         dldsdev2
         dldsproto1
         dldsproto2
         dldsproto3
         dlapwls1
         dlaptascob1    
         dlaptascob2
         tlapwls1
         dlaporalb1
         tlaporalb1
         dlaporalb2
         tlaporalb2
         
        
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Reboots
- name: Reboot of Dev Servers
  gather_facts: true
  become: true
  become_user: root
  hosts: pdl6sftp01
         dlissplunk1
         dldsadmin1
         dldsadmin2
         dldsansible2
         dldsdev1
         dldsdev2
         dldsproto1
         dldsproto2
         dldsproto3
         dlapwls1
         dlaptascob1    
         dlaptascob2
         tlapwls1
         #dlaporalb1
         #tlaporalb1
         #dlaporalb2
         #tlaporalb2
                  
  tasks:
  - name: Reboot Dev
    reboot:

# EOF Complete
