---
- name: Dev Yum updates 
  gather_facts: false
  become: true
  become_user: root
  
  hosts: pdl6sftp01
         dldsadmin1
         dldsadmin2
         dldsansible2
         dldsdev1
         dldsdev2
         dldsproto1
         dldsproto2
         dldsproto3
         dlapwls1
         dldboran1
         dldboran2
         dlaptascob1    
         dlaptascob2
         tlapwls1
         tldboran1
         tldboran2
         dlaporalb1
         tlaporalb1
         dlaporalb2
         tlaporalb2
        
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        
