---
- name: Validate all updates have been applied to DEV and SYSTEST
  hosts: dldsadmin1
 
  tasks:
  - name: Final Check
    shell: echo "Updates Successfully Applied."
    #shell: "yum check-update"
    #register: yumstatus
  #- debug:
      #var: yumstatus.stdout_lines
