---
- name: Hello World!
  hosts: dldsproto1 
  tasks:
 
  - name: Hello World!
    #hosts: dldsproto1
    shell: echo "Hi! Ansible is working."

- name: Hello Again!
  hosts: dldsproto2
  tasks:

  - name: Hello World!
    shell: echo "Hi! Hello Again."

- name: Hello Friend
  hosts: dldsproto3
  tasks:
  
  - name: Hello Friend
    shell: echo "Hello Friend" 
