---
- name: Pre Check to check Communication and Access
  hosts: dldsadmin1
 
  tasks:
  - name: Pre Check
    #shell: echo "Hi! Tower is working."
    shell: "yum check-update"
    register: yumstatus
  - debug:
    var: yumstatus.stdout_lines
