---
# Playbook to apply the latest RHEL updatesand Reboots for TAS Prod Training

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot all PROD TAS Training Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: plaptrngcob1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2

- name: Yum Apply Updates 
  gather_facts: false
  become: true
  become_user: root    
  hosts: plaptrngcob1
         plaptrngwls1
         pldbtrngoran1
                                   
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Stop the Training Database 
- name: Stop Training DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: pldbtrngoran1
  tasks:
    - name: Stopping DB
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines  
 
  
## Reboot Training Servers
- name: OEM and Training Servers
  gather_facts: true
  become: true
  become_user: root
  hosts: plaptrngcob1
         plaptrngwls1
         pldbtrngoran1         
  tasks:
  - name: Reboot
    reboot: 
    
    
## Pause to let InfoSec tools load  
- name: Pasue After Reboot
  gather_facts: false
  hosts: plaptrngcob1
         plaptrngwls1
         pldbtrngoran1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
  - name: Ping to verify connectivity
    ansible.builtin.ping:
    
  
## Start Training Server Database       
- name: Start Training DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: pldbtrngoran1
  tasks:
    - name: Starting DB
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines  
          
# Training Servers Complete
# EOF Complete
