---
# Playbook to apply the latest RHEL updates, switch Load Balancers and Reboots for TAS Prod OEM Servers

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot all PROD TAS OEM Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: plaporaoem1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2

- name: Yum Apply Updates 
  gather_facts: false
  become: true
  become_user: root    
  hosts: plaporaoem1
         pldboraoem1
                                            
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      


## Stop OEM and Training Servers       
- name: Stop OEM App
  gather_facts: false
  become: true
  become_user: oracle
  hosts: plaporaoem1
  tasks:
    - name: Stopping App
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 

- name: Stop OEM DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: pldboraoem1
  tasks:
    - name: Stopping DB
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 


## Reboot OEM and Training Servers
- name: OEM and Training Servers
  gather_facts: true
  become: true
  become_user: root
  hosts: plaporaoem1
         pldboraoem1                  
  tasks:
  - name: Reboot
    reboot: 
        
## Pause to let InfoSec tools load  
- name: Pasue After Reboot
  gather_facts: false
  hosts: plaporaoem1
         pldboraoem1         
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
  - name: Ping to verify connectivity
    ansible.builtin.ping:
 
## Start OEM and Training Servers       
- name: Start OEM DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: pldboraoem1
  tasks:
    - name: Start DB
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 

- name: Start OEM App
  gather_facts: false
  become: true
  become_user: oracle
  hosts: plaporaoem1
  tasks:
    - name: Starting App
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 
        
# OEM and Training Servers Complete
# EOF
