---
# Playbook to apply the latest RHEL updates and reboots in PROD
# TAS Prod servers will be updated but not rebooted

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot(exculding TAS) all PROD Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: pldsmgmt1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
 
- name: Yum Apply Updates TAS
  gather_facts: false
  become: true
  become_user: root    
  hosts: plaporaoem1
         pldboraoem1
         plapwls1
         plapwls2
         plapwls3
         plapwl1
         plapwl2
         plapwl3
         plaptascob1
         plaptascob2
         pldboran1
         pldboran2
         plaptrngcob1
         plaptrngwls1
         pldbtrngoran1
         plaporalb1
         plaporalb2
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      
      
- name: Yum Apply Updates Non TAS 
  gather_facts: false
  become: true
  become_user: root    
  hosts: pldsmgmt1
         pldsmta1
         plissplnkmst1
         plissplnkdeploy1
         plissplnksearch1
         plissplnkfwd1
         plissplnkidx1
         plissplnkidx2
         plissyslogng
         plissyslogng1
         plissyslogng2
         plissyslogngext
         plissyslogngint
         plntnetbx1
         pldsadmin1
         plisseccen1
         plissecnfs1
         plzeairwcgr1
         plziairwcge1
         #plapsftp1
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Stop Splunk before rebooting        
- name: Stop Splunk
  gather_facts: false
  become: true
  become_user: splunk
  hosts: plissplnkmst1
         plissplnkdeploy1
         plissplnksearch1
         plissplnkfwd1
         plissplnkidx1
         plissplnkidx2        
  tasks:
    - name: Stop Splunk
      shell: "/opt/splunk/bin/splunk stop"              
      register: status
    - debug:
       var: status.stdout_lines 

# Reboot
- name: Reboot Prod Servers exculding TAS
  gather_facts: false
  become: true
  become_user: root
  hosts: pldsmgmt1
         pldsmta1
         plissplnkmst1
         plissplnkdeploy1
         plissplnksearch1
         plissplnkfwd1
         plissplnkidx1
         plissplnkidx2
         plissyslogng
         plissyslogng1
         plissyslogng2
         plissyslogngext
         plissyslogngint
         plntnetbx1
         pldsadmin1
         plisseccen1
         plissecnfs1
         plzeairwcgr1
         plziairwcge1 
         #plapsftp1
  tasks:
  - name: Reboot Servers
    reboot: 
 
# Verfiy all servers on online    
- name: Ping Check
  gather_facts: false
  hosts: pldsmgmt1
         pldsmta1
         plissplnkmst1
         plissplnkdeploy1
         plissplnksearch1
         plissplnkfwd1
         plissplnkidx1
         plissplnkidx2
         plissyslogng
         plissyslogng1
         plissyslogng2
         plissyslogngext
         plissyslogngint
         plntnetbx1
         pldsadmin1
         plisseccen1
         plissecnfs1
         plzeairwcgr1
         plziairwcge1
         #plapsftp1
  tasks:
  - name: Pause for 1 minutes
    pause:
      minutes: 1
  - name: Ping to verify connectivity
    ansible.builtin.ping:

# Verify Splunk is running       
- name: Stauts Splunk
  gather_facts: false
  become: true
  become_user: splunk
  hosts: plissplnkmst1
         plissplnkdeploy1
         plissplnksearch1
         plissplnkfwd1
         plissplnkidx1
         plissplnkidx2        
  tasks:
    - name: Status Splunk
      shell: "/opt/splunk/bin/splunk status"              
      register: status
    - debug:
       var: status.stdout_lines 

# All complete EOF
