---
# Playbook to apply the latest RHEL updates, for TAS Prod WebLic and Cobol

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot the WebLogic and Cobol PROD TAS Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: plapwls1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2

- name: Yum Apply Updates 
  gather_facts: false
  become: true
  become_user: root    
  hosts: plapwls1
         plapwls2
         plapwls3
         plaptascob1
         plaptascob2
                                            
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Reboot
- name: Reboot WebLogic and Cobol Servers
  gather_facts: true
  become: true
  become_user: root
  hosts: plapwls1
         plapwls2
         plapwls3
         plaptascob1
         plaptascob2
                                   
  tasks:
  - name: Reboot WebLogic and Cobol Servers
    reboot: 

# EOF
