---
- name: Prod Yum updates 
  gather_facts: false
  become: true
  become_user: root
  hosts: pldsadmin1
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
