---
# Whoami       
- name: Whoami
  gather_facts: false
  hosts: qlaptascob1
         qlaptascob2
  tasks:
    - name: whoami
      command: whoami                             
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines

# Demand Daemon Status       
- name: Demand Daemon Status
  gather_facts: false
  hosts: qlaptascob1
         qlaptascob1
  tasks:
    - name: Demand Daemon Status
      shell: /tas/opt/scripts/chkdaemon              
      register: daemonstatus
    - debug:
       var: daemonstatus.stdout_lines 

# Demand Daemon Start       
#- name: Demand Daemon Status
#  gather_facts: false
#  hosts: qlaptascob1
#         qlaptascob1
#  tasks:
#    - name: Demand Daemon Status
#      shell: /tas/opt/scripts/startdemon               
#      register: daemonstatus
#    - debug:
#       var: daemonstatus.stdout_lines 

# Demand Daemon Status       
#- name: Demand Daemon Status
#  gather_facts: false
#  hosts: qlaptascob1
#         qlaptascob1
#  tasks:
#    - name: Demand Daemon Status
#      shell: /tas/opt/scripts/chkdaemon              
#      register: daemonstatus
#    - debug:
#       var: daemonstatus.stdout_lines 
