---
# Playbook to apply the latest RHEL updates, switch Load Balancers and Reboots in QUAT

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot all QUAT Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: qlaporalb1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2

- name: Yum Apply Updates Non DB 
  gather_facts: false
  become: true
  become_user: root    
  hosts: qlapwls1
         qlapwls2
         qlapwls3
         qlapwl1
         qlapwl2
         qlapwl3
         qlaptascob1    
         qlaptascob2
         qlaporalb1
         qlaporalb2
         qlapsftp1                         
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Reboot
- name: Reboot Non DB Servers
  gather_facts: false
  become: true
  become_user: root
  hosts: qlapwls1
         qlapwls2
         qlapwls3
         qlapwl1
         qlapwl2
         qlapwl3
         qlaptascob1    
         qlaptascob2
         qlaporalb1
         qlaporalb2
         qlapsftp1
  tasks:
  - name: Reboot Non DB Servers
    reboot: 

# Stop Secondary Oracle Database        
- name: Stop Secondary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran2
  tasks:
    - name: Stopping DB
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 
 
# Switch Seconday DB Traffic to Primary
- name: Swich Secondary LB to Primary
  gather_facts: false
  become: yes
  hosts: qlaporalb2  
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
  
#  Yum Apply Updates 
- name: Yum Apply Updates 
  gather_facts: false
  become: true
  become_user: root    
  hosts: qldboran2
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      
 
# Reboot Secondary Oracle Database
- name: Reboot Secondary Oracle Database
  gather_facts: false
  become: true
  become_user: root
  hosts: qldboran2          
  tasks:
  - name: Reboot Secondary Oracle Database
    reboot: 
    
# Pause to let InfoSec tools load    
- name: Pasue After Reboot
  gather_facts: false
  hosts: qldboran2
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
  - name: Ping to verify connectivity
    ansible.builtin.ping:
  
# Start Secondary Oracle Database        
- name: Start Secondary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran2
  tasks:
    - name: Starting DB
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout
      
# Switch Seconday DB Traffic to Secondary
- name: Swich Secondary LB to Secondary
  gather_facts: false
  become: yes
  hosts: qlaporalb2   
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
  
# Secondary DB complete
# Starting Primary DB

# Stop Primary Oracle Database        
- name: Stop Primay Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran1
  tasks:
    - name: Stopping DB
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 
 
# Switch Primary DB Traffic to Secondary
- name: Swich Primary LB to Secondary
  gather_facts: false
  become: yes
  hosts: qlaporalb1  
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines

#  Yum Apply Updates 
- name: Yum Apply Updates 
  gather_facts: false
  become: true
  become_user: root    
  hosts: qldboran1
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Reboot Primary Oracle Database
- name: Reboot Primary Oracle Database
  gather_facts: false
  become: true
  become_user: root
  hosts: qldboran1          
  tasks:
  - name: Reboot Primary Oracle Database
    reboot: 
    
# Pause to let InfoSec tools load    
- name: Pasue After Reboot
  gather_facts: false
  hosts: qldboran1
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2
  - name: Ping to verify connectivity
    ansible.builtin.ping:
  
# Start Primary Oracle Database        
- name: Start Secondary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran1
  tasks:
    - name: Starting DB
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout
      
# Switch Primary DB Traffic to Primary
- name: Swich Primary LB to Primary
  gather_facts: false
  become: yes
  hosts: qlaporalb1   
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
# DBs Complete

# Start Demand Deamons
#- name: Demand Daemon Start
#  gather_facts: false
#  become: true
#  become_user: tasmstr
#  hosts: qlaptascob1
#         qlaptascob2
#  tasks:
#    - name: Demand Daemon Start
#      shell: /tas/opt/scripts/startdemon               
#      register: daemonstatus
#    - debug:
#       var: daemonstatus.stdout_lines 

# Demand Daemon Status       
#- name: Demand Daemon Status
#  gather_facts: false
#  become: true
#  become_user: tasmstr
#  hosts: qlaptascob1
#         qlaptascob2
#  tasks:
#    - name: Demand Daemon Status
#      shell: /tas/opt/scripts/chkdaemon              
#      register: daemonstatus
#    - debug:
#       var: daemonstatus.stdout_lines 

# EOF Complete
