---
# Playbook to apply the latest RHEL updates, switch Load Balancers and Reboots in QUAT

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will update and reboot all QUAT Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: tql6sftp01
  tasks:
  - name: Pause for 2 minutes
    pause:
      minutes: 2

- name: Yum Apply Updates 
  gather_facts: false
  become: true
  become_user: root    
  hosts: tql6sftp01
         qlapwls1
         qlapwls2
         qlapwls3
         qldboran1
         qldboran2
         qlaptascob1    
         qlaptascob2      
                         
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest      

# Reboot
- name: Reboot Non DB Servers
  gather_facts: true
  become: true
  become_user: root
  hosts: tql6sftp01
         qlapwls1
         qlapwls2
         qlapwls3
         qlaptascob1    
         qlaptascob2          
  tasks:
  - name: Reboot Non DB Servers
    reboot: 

# Switch Seconday DB Traffic to Primary
- name: Swich Secondary LB to Primary
  gather_facts: false
  become: yes
  hosts: qldboran2  
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
        
# Stop Secondary Oracle Database        
- name: Stop Secondary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran2
  tasks:
    - name: Stopping DB
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 

# Temporary pause to verify DB stop   
- name: Double Check DB
  gather_facts: false
  hosts: qldboran2
  tasks:
  - name: Pause for 5 minutes
    pause:
      minutes: 5
   
# Reboot Secondary Oracle Database
- name: Reboot Secondary Oracle Database
  gather_facts: true
  become: true
  become_user: root
  hosts: qldboran2          
  tasks:
  - name: Reboot Secondary Oracle Database
    reboot: 
    
# Pause to let InfoSec tools load    
- name: Pasue After Reboot
  gather_facts: false
  hosts: qldboran2
  tasks:
  - name: Pause for 5 minutes
    pause:
      minutes: 5
  - name: Ping to verify connectivity
    ansible.builtin.ping:
  
# Start Secondary Oracle Database        
- name: Start Secondary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran2
  tasks:
    - name: Starting DB
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout
      
# Switch Seconday DB Traffic to Secondary
- name: Swich Secondary LB to Secondary
  gather_facts: false
  become: yes
  hosts: qldboran2  
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
  
# Secondary DB complete
# Starting Primary DB
 
# Switch Primary DB Traffic to Secondary
- name: Swich Primary LB to Secondary
  gather_facts: false
  become: yes
  hosts: qldboran1  
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
        
# Stop Primary Oracle Database        
- name: Stop Secondary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran1
  tasks:
    - name: Stopping DB
      shell: /home/oracle/scripts/dbs_shutdown.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout_lines 

# Temporary pause to verify DB stop   
- name: Double Check DB
  gather_facts: false
  hosts: qldboran1
  tasks:
  - name: Pause for 5 minutes
    pause:
      minutes: 5
 
# Reboot Primary Oracle Database
- name: Reboot Primary Oracle Database
  gather_facts: true
  become: true
  become_user: root
  hosts: qldboran1          
  tasks:
  - name: Reboot Primary Oracle Database
    reboot: 
    
# Pause to let InfoSec tools load    
- name: Pasue After Reboot
  gather_facts: false
  hosts: qldboran1
  tasks:
  - name: Pause for 5 minutes
    pause:
      minutes: 5
  - name: Ping to verify connectivity
    ansible.builtin.ping:
  
# Start Secondary Oracle Database        
- name: Start Primary Oracle DB
  gather_facts: false
  become: true
  become_user: oracle
  hosts: qldboran1
  tasks:
    - name: Starting DB
      shell: /home/oracle/scripts/dbs_startup.ksh              
      register: dbstatus
    - debug:
       var: dbstatus.stdout 
      
# Switch Primary DB Traffic to Primary
- name: Swich Primary LB to Primary
  gather_facts: false
  become: yes
  hosts: qldboran1  
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines

# All Complete EOF
